// AUTO-GENERATED by scripts/sync_to_api.py — 2026-03-12T09:50:03Z
// DO NOT EDIT MANUALLY — run: python3 scripts/sync_to_api.py

export const REAL_SIGNALS = [
  { topic: "LLM Infrastructure", stage: "accelerating", confidence: 0.98, impact_score: 0.93, evidenceCount: 16, sources: ["arxiv:cs.AI", "arxiv_rss"], proof_id: "research-2026-03-12-2603.10384", source_url: "https://arxiv.org/abs/2603.10384", category: "AI Research", first_seen: "2026-03-12" },
  { topic: "AI Agents", stage: "accelerating", confidence: 0.9000000000000001, impact_score: 0.9, evidenceCount: 4, sources: ["github:trending"], proof_id: "research-2026-03-12-gh-langflow-ai-langf", source_url: "https://github.com/langflow-ai/langflow", category: "AI Research", first_seen: "2026-03-12" },
  { topic: "Diffusion Models", stage: "accelerating", confidence: 0.77, impact_score: 0.81, evidenceCount: 2, sources: ["github:trending"], proof_id: "research-2026-03-12-gh-AUTOMATIC1111-sta", source_url: "https://github.com/AUTOMATIC1111/stable-diffusion-webui", category: "AI Research", first_seen: "2026-03-12" },
  { topic: "AI Reasoning", stage: "forming", confidence: 0.73, impact_score: 0.68, evidenceCount: 2, sources: ["arxiv:cs.AI", "arxiv_rss"], proof_id: "research-2026-03-12-2603.10359", source_url: "https://arxiv.org/abs/2603.10359", category: "AI Research", first_seen: "2026-03-12" },
  { topic: "Efficient AI", stage: "forming", confidence: 0.73, impact_score: 0.68, evidenceCount: 2, sources: ["arxiv:cs.LG", "arxiv_rss"], proof_id: "research-2026-03-12-2603.09983", source_url: "https://arxiv.org/abs/2603.09983", category: "AI Research", first_seen: "2026-03-12" },
  { topic: "Reinforcement Learning", stage: "emerging", confidence: 0.69, impact_score: 0.64, evidenceCount: 1, sources: ["arxiv:cs.LG", "arxiv_rss"], proof_id: "research-2026-03-12-2603.10009", source_url: "https://arxiv.org/abs/2603.10009", category: "AI Research", first_seen: "2026-03-12" },
  { topic: "AI Coding", stage: "emerging", confidence: 0.69, impact_score: 0.64, evidenceCount: 1, sources: ["arxiv:cs.CL", "arxiv_rss"], proof_id: "research-2026-03-12-2603.09982", source_url: "https://arxiv.org/abs/2603.09982", category: "AI Research", first_seen: "2026-03-12" },
];

export const DATA_META = {
  updated_at:       "2026-03-12",
  synced_at:        "2026-03-12T09:50:03Z",
  signal_count:     7,
  inputs_hash:      REAL_SIGNALS.map(s => s.proof_id).join("|").split("").reduce((a,c)=>((a<<5)-a+c.charCodeAt(0))|0,0).toString(16).replace("-",""),
  source:           "arxiv_rss + github_trending + pipeline",
  pipeline_version: "v1.1.0",
};

export function getSignals({ stage, limit } = {}) {
  let s = [...REAL_SIGNALS];
  if (stage) s = s.filter(x => x.stage === stage);
  s.sort((a,b) => b.confidence - a.confidence);
  if (limit) s = s.slice(0, parseInt(limit));
  return s;
}

export function getTopics() {
  return REAL_SIGNALS.map(s => ({
    id:         s.topic.toLowerCase().replace(/\s+/g, '-'),
    name:       s.topic,
    stage:      s.stage,
    confidence: s.confidence,
    proof_id:   s.proof_id,
    source_url: s.source_url,
    updated_at: DATA_META.updated_at,
  }));
}

export function getTrends({ limit } = {}) {
  const stageScore = { accelerating:1.0, peak:0.9, forming:0.7, emerging:0.5, fading:0.3, weak:0.1 };
  return REAL_SIGNALS.map(s => ({
    topic:       s.topic,
    stage:       s.stage,
    trend_score: parseFloat((s.confidence * (stageScore[s.stage] || 0.5)).toFixed(3)),
    velocity:    parseFloat((s.evidenceCount / 10).toFixed(2)),
    confidence:  s.confidence,
    proof_id:    s.proof_id,
    source_url:  s.source_url,
    updated_at:  DATA_META.updated_at,
  })).sort((a,b) => b.trend_score - a.trend_score).slice(0, limit ? parseInt(limit) : 20);
}

export function getEvents({ topic, limit } = {}) {
  let s = [...REAL_SIGNALS];
  if (topic) s = s.filter(x => x.topic.toLowerCase().includes(topic.toLowerCase()));
  if (limit) s = s.slice(0, parseInt(limit));
  return s.map((x, i) => ({
    event_id:      `evt_${String(i+1).padStart(3,'0')}`,
    topic:          x.topic,
    stage:          x.stage,
    probability:    x.confidence,
    evidence_count: x.evidenceCount,
    evidence_refs:  [x.proof_id],
    proof_id:       x.proof_id,
    source_url:     x.source_url,
    updated_at:     DATA_META.updated_at,
    timestamp:      new Date().toISOString(),
  }));
}

export function getEvent(id) {
  const idx = parseInt((id || '').replace('evt_',''), 10) - 1;
  if (idx >= 0 && idx < REAL_SIGNALS.length) {
    const x = REAL_SIGNALS[idx];
    return {
      event_id:       id,
      topic:           x.topic,
      stage:           x.stage,
      probability:     x.confidence,
      evidence_count:  x.evidenceCount,
      evidence_refs:   [x.proof_id],
      proof_id:        x.proof_id,
      source_url:      x.source_url,
      snapshot_url:    x.source_url,
      updated_at:      DATA_META.updated_at,
    };
  }
  return null;
}
